alicious_florist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import create_mood_flutter, show_main, create_flower, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register
from main.views import login_user
from main.views import logout_user
from main.views import edit_flower
from main.views import delete_flower
from main.views import add_flower_entry_ajax
 
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-flower', create_flower, name='create_flower'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-flower/<uuid:id>', edit_flower, name='edit_flower'),
    path('delete/<uuid:id>', delete_flower, name='delete_flower'), # sesuaikan dengan nama fungsi yang dibuat
    path('create-flower-entry-ajax', add_flower_entry_ajax, name='add_flower_entry_ajax'),
    path('create-flutter/', create_mood_flutter, name='create_mood_flutter'),
]

main/models.py
import uuid  # tambahkan baris ini di paling atas
from django.db import models
from django.contrib.auth.models import User

class Shop(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # tambahkan baris ini
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    flower = models.CharField(max_length=255)  
    quantity = models.IntegerField()  

class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)

class Employee(models.Model):
    department = models.CharField(max_length=100)
    project = models.ManyToManyField(Project)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Shop
from django.utils.html import strip_tags

class ShopForm(ModelForm):
    class Meta:
        model = Shop
        fields = ["name", "price", "description", "flower", "quantity"]

    def clean_flower(self):
        flower = self.cleaned_data["flower"]
        return strip_tags(flower)

    def clean_price(self):
        price = self.cleaned_data["price"]
        return strip_tags(price)
    

main/views.py
import json
from django.http import JsonResponse
import datetime
from django.utils.html import strip_tags
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render, redirect, reverse   # Tambahkan import redirect di baris ini
from main.forms import ShopForm
from main.models import Shop

@login_required(login_url='/login')
def show_main(request):

    context = {
        'name': request.user.username,
        'class': 'PBP A',
        'npm': '2306245642',
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_flower(request):
    form = ShopForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        flower_entry = form.save(commit=False)
        flower_entry.user = request.user
        flower_entry.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_flower.html", context)

def show_xml(request):
    data = Shop.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Shop.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Shop.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Shop.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
      else:
        messages.error(request, "Invalid username or password. Please try again.")
      
   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_flower(request, id):
    # Get flower entry berdasarkan id
    flower = Shop.objects.get(pk = id)

    # Set flower entry sebagai instance dari form
    form = ShopForm(request.POST or None, instance=flower)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_flower.html", context)

def delete_flower(request, id):
    # Get flower berdasarkan id
    flower = Shop.objects.get(pk = id)
    # Hapus flower
    flower.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_flower_entry_ajax(request):
    name = strip_tags(request.POST.get("name")) # strip HTML tags!
    price = strip_tags(request.POST.get("price")) # strip HTML tags!
    description = strip_tags(request.POST.get("description")) # strip HTML tags!
    flower = strip_tags(request.POST.get("flower")) # strip HTML tags!
    quantity = request.POST.get("quantity")
 
    new_flower = Shop(
        name=name, 
        price=price,
        description=description,
        flower=flower,
        quantity=quantity
    )
    new_flower.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_mood_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_mood = Shop.objects.create(
            user=request.user,
            mood=data["mood"],
            mood_intensity=int(data["mood_intensity"]),
            feelings=data["feelings"]
        )

        new_mood.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/bebas.html
- judul
- sub judul
- deskripsi singkat (paragraf)
- data mahasiswa (nama, npm)

<h1>Alicious Florist</h1>
<h5>Toko Bunga Alicious</h5>
<p>Merupakan toko bunga favoritmu!</p>

<table>
    <tr>
        <th>Nama</th>
        <th>NPM</th>
    </tr>
    <tr>
        <td>Alica</td>
        <td>2306</td>
    </tr>
</table>

main/templates/card_flower.html
<div class="relative break-inside-avoid">
    <div class="relative bg-pink-100 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-[#DB7093] transform rotate-1 hover:rotate-0 transition-transform duration-300">
        <div class="bg-[#DB7093] text-pink-1000 p-4 rounded-t-lg">
            <h3 class="font-bold text-xl mb-2">Thank you for your order, {{flower_entry.name}} !</h3>
        </div>
        <div class="p-4">
            <p class="font-semibold text-lg mb-2">You just ordered {{flower_entry.flower}}</p> 
            <p class="text-gray-700 mb-2">
                <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px),#CDC1FF_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1">{{flower_entry.feelings}}</span>
            </p>
            <div class="mt-4">
                <div class="relative pt-1">
                    <!-- Harga Produk -->
                    <div class="flex mb-2 items-center justify-between">
                        <div>
                            <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-green-600 bg-green-200">
                                Price: Rp {{flower_entry.price}}
                            </span>
                        </div>
                    </div>
                    
                    <!-- Kuantitas Produk -->
                    <div class="flex mb-2 items-center justify-between">
                        <div>
                            <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-blue-600 bg-blue-200">
                                Quantity: {{flower_entry.quantity}} pcs
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Buttons Section -->
        <div class="flex justify-center space-x-4 mt-4 mb-4">
            <a href="{% url 'main:edit_flower' flower_entry.pk %}" class="bg-[#DEB887] hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                </svg>
            </a>
            <a href="{% url 'main:delete_flower' flower_entry.pk %}" class="bg-[#A52A2A] hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                </svg>
            </a>
        </div>
    </div>
</div>

main/templates/card_info.html
<div class="bg-gradient-to-r from-pink-500 to-[#FFE4E1] p-4 rounded-lg shadow-lg">
    <div class="p-4 animate-shine">
      <h5 class="text-lg font-semibold text-gray-200">{{ title }}</h5>
      <p class="text-white">{{ value }}</p>
    </div>
</div>

main/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center w-screen bg-[#FAFAD2] py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <img src="{% static 'image/logo-pink.png' %}" alt="Logo" class="mx-auto h-28 w-auto"/> 
      <h2 class="mt-0 text-center text-black text-3xl font-extrabold text-gray-900">
        Login to your account
      </h2>
    </div>
    <form class="mt-8 space-y-6" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-pink-500 focus:border-pink-500 focus:z-10 sm:text-sm" placeholder="Username">
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-pink-500 focus:border-pink-500 focus:z-10 sm:text-sm" placeholder="Password">
        </div>
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-[#DB7093] hover:bg-pink-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500">
          Sign in
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4">
      <p class="text-sm text-black">
        Don't have an account yet?
        <a href="{% url 'main:register' %}" class="font-medium text-pink-400 hover:text-pink-500">
          Register Now
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Alicious Florist</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
{% include 'navbar.html' %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-[#FAFAD2] flex flex-col">
  <div class="p-2 mb-7 relative">
    <!-- Greeting message image on the right -->
    <div class="flex items-center justify-center">
      <img src="{% static 'image/greeting.png' %}" alt="Greeting Message" class="w-50 h-auto">
    </div>
    <div class="grid place-items-center justify-center">
      <!-- Combined NPM, Name, and Class into one block on the left -->
      <div class="col-span-3 md:col-span-1">
        <div class="w-64 p-4 bg-pink-200 rounded-lg shadow-lg">
          <p class="text-lg font-bold text-gray-700">Name: {{ name }}</p>
          <p class="text-lg font-bold text-gray-700">NPM: {{ npm }}</p>
          <p class="text-lg font-bold text-gray-700">Class: {{ class }}</p>
        </div>
      </div>
    </div>  
  </div>

  <!-- Last Login Section -->
  <div class="grid place-items-center justify-center mb-6">
    <div class="flex rounded-md items-center bg-[#FF69B4] py-3 px-4 w-fit">
      <h1 class="text-white text-center">Last Login: {{last_login}}</h1>
    </div>
  </div>

  <!-- Card Demo -->
  <div class="grid place-items-center justify-center mb-6">
    <div class="flex-col rounded-md items-center bg-[#FF69B4] py-3 px-4 w-fit">
      <h1 class="text-white text-center">Judul Card</h1>
      <img src="{% static 'image/logo-white.png' %}" alt="Gambar" class="card-image">
      <p class="text-lg text-white-700 text-center">Halo aku adalah deskripsi card Demo PBP!</p>
  </div>

  <!-- Add New Flower Entry Button -->
  <div class="grid place-items-center justify-center mb-14">
    <a href="{% url 'main:create_flower' %}" class="bg-pink-600 hover:bg-pink-700 text-white font-bold py-1/2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 mb-4">
      Add New Flower Entry
    </a>
    <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-pink-500 hover:bg-pink-00 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
      Add New Flower Entry by AJAX
    </button>
  </div>

  <div id="flower_entry_cards"></div>

  <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
    <div id="crudModalContent" class="relative bg-[#FFFFE0] rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900">
          Add New Flower Entry
        </h3>
        <button type="button" class="text-pink-400 bg-transparent hover:bg-pink-200 hover:text-black-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div class="px-6 py-4 space-y-6 form-style">
        <form id="shopForm">
          <div class="mb-4">
            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
            <input type="text" id="name" name="name" class="mt-1 block w-full border border-pink-300 rounded-md p-2 hover:border-pink-700" placeholder="Please enter your name, love" required>
          </div>
          <div class="mb-4">
            <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
            <input type="number" id="price" name="price" class="mt-1 block w-full border border-pink-300 rounded-md p-2 hover:border-pink-700" placeholder="Enter price" required>
          </div>
          <div class="mb-4">
            <label for="description" class="block text-sm font-medium text-gray-700">Description</label>
            <textarea id="text" id="name" name="name" class="mt-1 block w-full border border-pink-300 rounded-md p-2 hover:border-pink-700" placeholder="Enter description" required></textarea>
          </div>
          <div class="mb-4">
            <label for="flower" class="block text-sm font-medium text-gray-700">Flower</label>
            <input type="text" id="flower" name="flower" class="mt-1 block w-full border border-pink-300 rounded-md p-2 hover:border-pink-700" placeholder="What kind of flower do you want?" required>
          </div>
          <div class="mb-4">
            <label for="quantity" class="block text-sm font-medium text-gray-700">Quantity</label>
            <input type="number" id="quantity" name="quantity" min="1" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-pink-700" placeholder="How much do you want?" required>
          </div>
        </form>
      </div>
      <!-- Modal footer -->
      <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
        <button type="button" class="bg-pink-600 hover:bg-pink-700 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
        <button type="submit" id="submitFlower" form="shopForm" class="bg-pink-600 hover:bg-pink-700 text-white font-bold py-2 px-4 rounded-lg">Save</button>
      </div>
    </div>
  </div>
</div>

<script>
  function addShop() {
    fetch("{% url 'main:add_flower_entry_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#shopForm')),
    })
    .then(response => refreshFlowerEntries())

    document.getElementById("shopForm").reset(); 
    document.querySelector("[data-modal-toggle='crudModal']").click();

    return false;
  }

  async function getFlowerEntries(){
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshFlowerEntries() {
      document.getElementById("flower_entry_cards").innerHTML = "";
      document.getElementById("flower_entry_cards").className = "";
      const flowerEntries = await getFlowerEntries();
      console.log(flowerEntries)
      let htmlString = "";
      let classNameString = "";
 
      if (flowerEntries.length === 0) {
          classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
          htmlString = `
              <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                  <img src="{% static 'image/sedih-banget.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
                  <p class="text-center text-gray-600 mt-4">Belum ada data pada Alicious Florist.</p>
              </div>
          `;
      }
      else {
          classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full"
          flowerEntries.forEach((item) => {
                const name = DOMPurify.sanitize(item.fields.name);
                const price = DOMPurify.sanitize(item.fields.price);
                const description = DOMPurify.sanitize(item.fields.description);
                const flower = DOMPurify.sanitize(item.fields.flower);
                const quantity = DOMPurify.sanitize(item.fields.quantity);
                
                htmlString += `
                <div class="relative break-inside-avoid">
                    <div class="relative bg-pink-100 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-[#DB7093] transform rotate-1 hover:rotate-0 transition-transform duration-300">
                        <div class="bg-[#DB7093] text-pink-1000 p-4 rounded-t-lg">
                            <h3 class="font-bold text-xl mb-2">Thank you for your order, ${item.fields.name} !</h3>
                    </div>
                    <div class="p-4">
                        <p class="font-semibold text-lg mb-2">You just ordered ${item.fields.flower}</p> 
                        <div class="mt-4">
                            <div class="relative pt-1">
                                <!-- Harga Produk -->
                                <div class="flex mb-2 items-center justify-between">
                                    <div>
                                        <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-green-600 bg-green-200">
                                            Price: Rp ${item.fields.price}
                                        </span>
                                    </div>
                                </div>
                                
                                <!-- Kuantitas Produk -->
                                <div class="flex mb-2 items-center justify-between">
                                    <div>
                                        <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-blue-600 bg-blue-200">
                                            Quantity: ${item.fields.quantity} pcs
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Buttons Section -->
                    <div class="flex justify-center space-x-4 mt-4 mb-4">
                        <a href="/edit-flower/${item.pk}" class="bg-[#DEB887] hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                            </svg>
                        </a>
                        <a href="/delete/${item.pk}" class="bg-[#A52A2A] hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-9 w-9" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 102 0V8a1 1 00-1-1z" clip-rule="evenodd" />
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
                  `;
          });
      }
      document.getElementById("flower_entry_cards").className = classNameString;
      document.getElementById("flower_entry_cards").innerHTML = htmlString;
  }

refreshFlowerEntries();
  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-95');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');

      setTimeout(() => {
        modal.classList.add('hidden');
      }, 150);  
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);
  document.getElementById("shopForm").addEventListener("submit", (e) => {
      e.preventDefault();
      addShop();
  })


  fetch('https:/aliciousflorist.com/data')
    .then(response => {
      console.log('Status:', response.status);
      if (response.ok) {
        return response.json();
      } else {
        throw new Error('Request failed, status: ${response.status}');
        }
      })
    .then(data => {
      console.log('Data:', data);
    })
    .catch(error => {
      console.error('Error:', error);
    });

</script>
{% endblock content %}